apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-frontend
  template:
    metadata:
      labels:
        app: sa-frontend
    spec:
      containers:
      - name: sa-frontend
        image: eu.gcr.io/welcome-to-k8s-042019/sa-frontend:k8s
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          exec:
            command:
            - ls
            - /usr/share/nginx/html/
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3